services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modulo04
    ports:
      - "5432:5432"
    volumes:
      - modulo04_postgres_data:/var/lib/postgresql/data

volumes:
  modulo04_postgres_data:
